env: test300000011112222333333344445555

spring:
#   application:
#     name: order-consumer-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/db2019?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
 
