env: test3

spring:
  application:
    name: order-consumer-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/db2019?characterEncoding=utf-8&useSSL=false
#   rabbitmq:
#     host: 10.1.100.34
#     port: 5672
#     username: test
#     password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
 
